In [2]:
import pandas as pd
import numpy as np
import re
import sklearn
import seaborn as sns
from collections import Counter
import warnings
import pickle
warnings.filterwarnings('ignore')

sns.set(style='white', context='notebook', palette='deep')
pd.options.display.max_columns = 100

from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold, learning_curve
from sklearn.feature_selection import SelectFromModel, SelectKBest
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble.gradient_boosting import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.externals import joblib

In [4]:
test2 = pd.read_csv("train.csv")
test2 = test2.rename(columns={'Unnamed: 0': 'Unknown',
                                  'SeriousDlqin2yrs': 'Target',
                                  'RevolvingUtilizationOfUnsecuredLines': 'UnsecLines',
                                  'NumberOfTime30-59DaysPastDueNotWorse': 'Late3059',
                                  'DebtRatio': 'DebtRatio',
                                  'MonthlyIncome': 'MonthlyIncome',
                                  'NumberOfOpenCreditLinesAndLoans': 'OpenCredit',
                                  'NumberOfTimes90DaysLate': 'Late90',
                                  'NumberRealEstateLoansOrLines': 'PropLines',
                                  'NumberOfTime60-89DaysPastDueNotWorse': 'Late6089',
                                  'NumberOfDependents': 'Deps'})
test2.drop(labels=["Target"],axis = 1,inplace=True)
test2.drop(labels=["Target"],axis = 1,inplace=True)
test2.head()

,Unknown,Target,UnsecLines,age,Late3059,DebtRatio,MonthlyIncome,OpenCredit,Late90,PropLines,Late6089,Deps
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [14]:
user_data= {'UnsecLines':[0.88551908], 'age':[43], 'Late3059':[0], 'DebtRatio':[0.1775], 'MonthlyIncome':[5700],'OpenCredit':[4], 'Late90':[0], 'PropLines':[0],'Late6089':[0], 'Deps':[0]}
test = pd.DataFrame(user_data)

In [15]:
test.head()

,UnsecLines,age,Late3059,DebtRatio,MonthlyIncome,OpenCredit,Late90,PropLines,Late6089,Deps
0,0.885519,43,0,0.1775,5700,4,0,0,0,0

In [ ]:
#test.UnsecLines = pd.qcut(test.UnsecLines.values, 0).codes
#test.age = pd.qcut(test.age.values, 0).codes
#test.MonthlyIncome = pd.qcut(test.MonthlyIncome.values, 0).codes
#test.DebtRatio = pd.qcut(test.DebtRatio.values, 0).codes
#test.OpenCredit = pd.qcut(test.OpenCredit.values, 0).codes